### ISSUE TITLE
Review frost paper and references to see if we can avoid extra round by using a different protocol

### ISSUE THREAD

**Issue by xoloki** [Trust-Machines/frost#11]

**Comment by a3slade** [comment]
The verdict:
One scheme would allow us to reduce the number of signing attempts by allowing us to accept any group of signatures without predesignating the T signers. However, it would require more data to be sent over the p2p during the set-up stage.

Another paper described a simpler scheme but it would require the public keys of all the signers to be included in the signature for verification and that is a def no go since we will have lots of stackers and the signature itself needs to go on the bitcoin chain.

**Comment by xoloki** [comment]
@a3slade concluded that the first scheme (PSDSS) would not be able to use one poly/nonce per signer, which makes it much less interesting.

Another paper (https://jit.ndhu.edu.tw/article/viewFile/2135/2148) describes an actual weighted threshold scheme.  It is somewhat complex, using a knapsack algorithm  and the Chinese remainder theorem.  I will try to do a prototype implementation and see if it's workable.
