### ISSUE TITLE
FROST Audit

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/frost#89]

**Comment by jo-tm** [comment]
@xoloki I read the WTF paper. I don't have any comments on the crypto, I can add a question about what happens with the Byzantine parties. Does the stacking protocol enforce some slashing on Byzantine WTF/FROST signers or what are the iterations to recover from this?

```Like many DKG schemes, FROST employs the technique of polynomial interpolation. But whereas traditional DKG protocols use a trusted dealer, FROST is a trustless protocol. To accomplish this, each party acts as a trusted dealer to every other party and runs a traditional DKG protocol. The parties then combine their keys trustlessly, and the result is a fully trustless distributed key, of which each party controls an equal share.```

**Q: Does the number of parties predetermined and fixed or a fraction of Byzantine parties cannot follow the protocol and be removed from the final set? What happens if `Each receiving party checks each private share for consistency with the public polynomial of the sending party` fails? Slashing of locked STX? Related to: `While FROST is optimized for a reduced number of rounds in the optimistic case of no byzantine actors`.**
